SCHEMA=${dbSchemaApp}
SCHEMA_EVT=${dbSchemaApp}
DOMAIN_NAME=${dName}
HIBERNATE_DIALECT=${hibernateDialect}


DB_DEFAULT_DRIVER=${dbDriver}
DB_DEFAULT_URL=${dbURL}
DB_DEFAULT_USERNAME=${dbApiUserName}
DB_DEFAULT_ENCODEDKEY=${dbApiEncoded}
DB_DEFAULT_TRANSACTION_ISOLATION=${dbTransaction}
DB_DEFAULT_LOGSQL=false


DB_LOGGING_DRIVER=${dbDriver}
DB_LOGGING_URL=${dbURL}
DB_LOGGING_USERNAME=${dbApiUserName}
DB_LOGGING_ENCODEDKEY=${dbApiEncoded}
DB_LOGGING_TRANSACTION_ISOLATION=${dbTransaction}


DB_ANALYTICS_DRIVER=${dbDriver}
DB_ANALYTICS_URL=${dbURL}
DB_ANALYTICS_USERNAME=${dbApiUserName}
DB_ANALYTICS_ENCODEDKEY=${dbApiEncoded}
DB_ANALYTICS_TRANSACTION_ISOLATION=${dbTransaction}


DB_EVENTS_DRIVER=${dbDriver}
DB_EVENTS_URL=${dbURL}
DB_EVENTS_USERNAME=${dbApiUserName}
DB_EVENTS_ENCODEDKEY=${dbApiEncoded}
DB_EVENTS_TRANSACTION_ISOLATION=${dbTransaction}


DB_STAGING_DRIVER=${dbDriver}
DB_STAGING_URL=${dbURL}
DB_STAGING_USERNAME=${dbApiUserName}
DB_STAGING_ENCODEDKEY=${dbApiEncoded}
DB_STAGING_TRANSACTION_ISOLATION=${dbTransaction}


ACTIVEMQ_BROKER_URL=${mqUrl}
ACTIVEMQ_USERNAME=${mqUserName}
ACTIVEMQ_ENCODEDKEY=${mqEncoded}


REDIS_HOST=${redisHost}
REDIS_PORT=6379
REDIS_ENCODEDKEY=${redisEncoded}
REDIS_SSL=false

STAGING_REDIS_HOST=${stagingRedisHost}
STAGING_REDIS_PORT=6379
STAGING_REDIS_ENCODEDKEY=${stagingRedisEncoded}
STAGING_REDIS_SSL=false

JOB_SERVER_BASE_URL=${jobServerUrl}
JOB_SERVER_EXT_BASE_URL=${jobServerUrl}

KEYSTORE_FILE_NAME=${keystoreFile}
KEYSTORE_PASSWORD_FILE_NAME=""
